(define (power a b)
  (if (= b 0)
    1
    (if (< b 0)
      (/ 1 (power a (-b)))
      (* a (power a (- b 1)))
      )
    )
  )

(display "Enter a:")
(let ((a (read)))
  (display "Enter b:")
  (let ((b (read)))
    (display "a^b = ")
    (display (power a b))
    (newline)
  )
)
