(define pi 3.14159)
;(display pi)
(define (sphereArea r)
  ( * (/ 4 3) pi (* r r r)))

(display "give radius of the sphere")
(newline)
(let ((r (read)))
  (display "r = ")
  (display r)
  (newline)
  (display "the volume of the sphera is: ")
  (display (sphereArea r))
  (newline))
